services:
  postgres:
    image: postgres:17
    container_name: sportsphere-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: sportsphere
      POSTGRES_PASSWORD: sportsphere_dev
      POSTGRES_DB: sportsphere

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: