"""add refund amount to bookings

Revision ID: 99b0fc3041f7
Revises: 745b4fa76521
Create Date: 2026-08-29 12:18:59.991656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b0fc3041f7'
down_revision: Union[str, Sequence[str], None] = '745b4fa76521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'bookings',
        sa.Column(
            'refund_amount',
            sa.Integer(),
            nullable=False,
            server_default='0',
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'refund_amount')
    # ### end Alembic commands ###
