"""add booking hold expiry

Revision ID: b7f17c0ccd57
Revises: 1553a017e1fd
Create Date: 2026-08-29 09:37:56.347099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f17c0ccd57'
down_revision: Union[str, Sequence[str], None] = '1553a017e1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('hold_expires_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_bookings_active_slot'), table_name='bookings', postgresql_where="((status)::text = 'confirmed'::text)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookings_active_slot'), 'bookings', ['slot_id'], unique=True, postgresql_where="((status)::text = 'confirmed'::text)")
    op.drop_column('bookings', 'hold_expires_at')
    # ### end Alembic commands ###
