"""add razorpay order id to payments

Revision ID: d1121b7636df
Revises: 99b0fc3041f7
Create Date: 2026-08-29 13:02:54.259944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1121b7636df'
down_revision: Union[str, Sequence[str], None] = '99b0fc3041f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('provider_order_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'provider_order_id')
    # ### end Alembic commands ###
